### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by vanityx** [vanityx/AlienGame#1]
'Event' object has no attribute 'key'

Issue with class variables, preventing the code from running.

> When trying to call a class function "slime.move(event, player.positionX)", the event variable is not recognised.

**Comment by almeister** [comment]
The issue here is that the event data depends on it's type.  From PyGame API:

![image](https://user-images.githubusercontent.com/7346924/83980252-0d88eb00-a90c-11ea-9b02-be1d35fc70cc.png)
https://www.pygame.org/docs/ref/event.html

If you look at where you're calling Slime.move(), you'll discover why event might not include the key attribute...
https://github.com/vanityx/AlienGame/blob/master/main.py#L81
